---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: cloudflared-tunnel-token
spec:
  encryptedData:
    tunnel-token: AgCYF3L7vKJHXY2+cxQHfejI2N9zu/ej8m/ddiaZfCt8qc6T3ji7H5WpSn4cMl/ziWAEspMfhrtKSkplW5SWonWGLmkDLXp1KiBJ7BHby7dLHMBgF+aMpJyAbfK3bB49yd8bAUrg5n9IdmermTHX6ryUTptvtAMMBK9Seb6h4QrZWA8v3yzTE7LLnfhxhNGf6uSYUjKg8KyMUPPDkMA3LU53fOyHiDFWfPkJSv/0tl0Yyo7yLF5Yye25bVjXPoujxy5FSHqov8rUzgB8tMmeQSeju2Q1BbHnG40IlKwlfcQl3FFjdv/v6DdfkU0UF5/p4L6PKwI9c3w6Khh24PY3YSgky4PFTtndzSd3z3b3uSqlQvFI82NCDjyiIK+MVaFsPN8I/N19UJEDNk9EoBYm8gbMruNftKefxenB1zFo/uXWJs8nagravyyTQ96MhwbJb7rzEz8c9T+Z0FflaR5vrtFDMVmRNPDg12LkcQSjoSn26hfGGfSV7EHmgqWnOhluppzlndlmTw3u0QlERH0YzLOUVHXG9w4RkaKRY3KDtNsiKz3LGvhZtlA36PrWobaHsRAElAAB3jrAZqUFthCnm7BpJq6eCUlLcs7pQUexFdg/+YwTD4g0FDy6/wFuGsdAWZUO50eItyXtMLsq72zhG0H9llQmEEU2DGOfzxM14mNnbH90V1CAdQe3ADvIeHxyPsKkXzYDnssQ9I0OmoCFIBgpqCrySdXVWuf+pVG237Ni2ffYAuFpIwlc40Wp2rDv4yWZoUOJcNCeziNin4nBq4/MGn1GeXGPB70YuC4GXvAjXG+oOSwFNXjX6vlCP4DfIiNbdQsFs2nzDaELH8F2i5kcmvski1c/gg/lvl64MsUyrG8bSUfSlI/7RdgfycgNHdRBtVSxwe2Ussok1luwEtmO40E0LfQJXFyqDtdw+hvLCgnLv1H8UHZE
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: cloudflared-tunnel-token
