apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - env.sealed.yaml
  - cloudflared-tunnel-token.sealed.yaml
  - cloudflared-tunnel.yaml
  - ../../base
images:
  - name: ghcr.io/jvizueta/lyra
    newTag: latest