apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: waha-env
spec:
  encryptedData:
    # WAHA_LICENSE: AgB...==        # optional (Core = can omit)
    WAHA_ADMIN_TOKEN: AgDIL3AIxgEX2yL1YnLn752NDDSjYWQe4p2S555hiBmdRJbCC1HQ9334WkYX7XzMkWOWuJ3FS4Faii4n8qM7ZjAmh2HFvP8QiOBb2zs4G3SlEt+tIq6SNSjVgIPKgLb/9Gm3AdAIhEwLGdQsARRC3KSIsxqjxOks0Tj1GBXK7Hg+pMlC7wy2V2qlV5ftnNnAxAX9QIX2jbndAzb3mGWlGqS3Fiode3E0hKdYySm0FnhyObn7nPt+F6GwG9ylGJMcns/M7SWdHacJ6Z5fRe4Ta3bj/+WnVz8Ucf69xf5XqrNTDJZ4xZDRoxqZuB74WT9v4P1l8dqhBVLKOkU2nTePRLN0ff1bbTikDn5etyFhtSTrqrg/V48lGLMIx8sSC770YNj8SVMhofLAqnnSkMgGaMgkB+YHb1cLJb4R8PdNcZ+H0CN/cH4HM6EnXkpeUSYjWIA36ZaLduL1DrjA3IgJZzHgkvhOBMyfVw4NaGCZXwH7OwJHhWl5UsrO7f/9MKldtmaA23Yw4sEEh2v5MVkGSJR4rlIXsaC7niIYIV1U1xsL2vzv+kwqkf0VqxoXpZYIPqbwSUvqWE1AhzciCGDaeQiOKpf25/e3spH0sd8MvMK5MEs701oGab+tk+8AJQBQ/03K8CE+DO+RP4vdVJmMesGXbv9LV28CPjOJY+ldB561f5NHc3sfTMRUqWRzR4YJq8H5FPpj1zarxNOlhv6owb6cD3TZPTxd8vP81mn7ZP3kwwNCDWGlFFbrDoTWPCI30zUF8tqPtbcUHDxA7j9hcgjY
  template:
    type: Opaque
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: waha-env
