apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: waha-data
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 1Gi
  storageClassName: "local-path"
