apiVersion: apps/v1
kind: Deployment
metadata:
  name: waha
  labels:
    app: waha
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: waha
  template:
    metadata:
      labels:
        app: waha
    spec:
      containers:
        - name: waha
          image: devlikeapro/waha:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 3000
          env:
            # Force WAHA to bind to all interfaces instead of just [::1]
            - name: WAHA_HOST
              value: "0.0.0.0"
            - name: WAHA_PORT
              value: "3000"
            # Disable authentication for development
            # - name: WAHA_HTTP_AUTHENTICATION_ENABLED
            #   value: "false"
          envFrom:
            - configMapRef:
                name: waha-config
            - secretRef:
                name: waha-env
          volumeMounts:
            - name: data
              mountPath: /app/data
          # -- only available in plus version
          # readinessProbe:
          #   httpGet:
          #     path: /health
          #     port: http
          #   initialDelaySeconds: 10
          #   periodSeconds: 10
          # livenessProbe:
          #   httpGet:
          #     path: /health
          #     port: http
          #   initialDelaySeconds: 20
          #   periodSeconds: 20
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: waha-data
