apiVersion: v1
kind: Service
metadata:
  name: waha
  labels:
    app: waha
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  type: ClusterIP
  selector:
    app: waha
  ports:
    - name: http
      port: 3000
      targetPort: http
