apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - env.cluster.sealed.yaml
  - ../../base
images:
  - name: ghcr.io/jvizueta/ai-customer-service/counter-agent
    newTag: dev-e7caf5bd628bbffe746df61120f8815ee704b05d
